# docker compose up
# docker compose down && docker compose up
services:
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    network_mode: host
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=pizzauser
      - POSTGRES_PASSWORD=Masterkey123
      - POSTGRES_DB=pizzadb      
    healthcheck:
      test: ["CMD", "pg_isready", "--host", "127.0.0.1", "--username", "pizzauser", "--port", "5432", "--dbname","pizzadb"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s 

  api:
    image: caravanacloud/pizza-api:latest
    container_name: api
    hostname: api
    network_mode: host
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://127.0.0.1:5432/pizzadb
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_OIDC_PROVIDER=${QUARKUS_OIDC_PROVIDER}
      - QUARKUS_OIDC_CLIENT_ID=${QUARKUS_OIDC_CLIENT_ID}
      - QUARKUS_OIDC_CREDENTIALS_SECRET=${QUARKUS_OIDC_CREDENTIALS_SECRET}
    depends_on:
      db:
        condition: service_healthy